apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: paparazzi
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: paparazzi
    spec:
      containers:
      - name: prague
        image: prague.azurecr.io/prague:626
        command:
          - 'node'
          - 'dist/paparazzi/index.js'
        env:
        - name: DEBUG
          value: "routerlicious:*"
        - name: NODE_ENV
          value: production
        volumeMounts:
        - name: config
          mountPath: /usr/src/server/config.json
          subPath: config.json
      imagePullSecrets:
      - name: regsecret
      volumes:
        - name: config
          configMap:
            name: prague
