apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: scriptorium
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: scriptorium
    spec:
      containers:
      - name: prague
        image: prague.azurecr.io/prague:565
        command:
          - 'npm'
          - 'run'
          - 'scriptorium'
        env:
        - name: DEBUG
          value: "routerlicious:*"
        - name: NODE_ENV
          value: production
        volumeMounts:
        - name: config
          mountPath: /usr/src/server/config.json
          subPath: config.json
      imagePullSecrets:
      - name: regsecret
      volumes:
        - name: config
          configMap:
            name: prague
