apiVersion: v1
kind: Service
metadata:
  name: tmz
  labels:
    app: tmz
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
    targetPort: ui
  selector:
    app: tmz
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: tmz
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: tmz
    spec:
      containers:
      - name: prague
        image: prague.azurecr.io/prague:562
        ports:
        - name: ui
          containerPort: 4000
        command:
          - 'npm'
          - 'run'
          - 'tmz'
        env:
        - name: DEBUG
          value: "routerlicious:*"
        - name: NODE_ENV
          value: production
        volumeMounts:
        - name: config
          mountPath: /usr/src/server/config.json
          subPath: config.json
      imagePullSecrets:
      - name: regsecret
      volumes:
        - name: config
          configMap:
            name: prague
