apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "gateway.fullname" . }}
  labels:
    app: {{ template "routerlicious.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: "{{ .Values.name }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  config.json: |
    {
        "logger": {
            "colorize": false,
            "morganFormat": "short",
            "json": true,
            "level": "info",
            "timestamp": false,
            "label": "winston"
        },
        "alfred": {
            "maxMessageSize": "16KB",
            "restJsonSize": "50mb",
            "key": "{{ .Values.alfred.key }}",
            "tenants": [
                {{- range $index, $tenant := .Values.alfred.tenants }}
                {{ toJson . }},
                {{- end }}
                {
                    "id": "prague",
                    "key": "43cfc3fbf04a97c0921fd23ff10f9e4b"
                },
                {
                    "id": "github",
                    "key": "0bea3f87c186991a69245a29dc3f61d2"
                },
                {
                    "id": "cobalt",
                    "key": "0e3c439e9ba63d85936c7e7e9c79478c"
                },
                {
                    "id": "local",
                    "key": "43cfc3fbf04a97c0921fd23ff10f9e4b"
                }
            ]
        },
        "login": {
            "enabled": true,
            "microsoft": {
                "clientId": "3d642166-9884-4463-8248-78961b8c1300",
                "secret": "IefegJIsumWtD1Of/9AIUWvm6ryR624vgMtKRmcNEsQ="
            },
            "accounts": [
                {
                    "username": "test",
                    "password": "mRTvhfDTE3FYbVc"
                }
            ]
        },
        "redis": {
            "host": "{{ .Values.redis.url }}",
            "port": 6379
        },
        "error": {
            "track": true,
            "endpoint" : "https://25f5c231660f474fb85fb4daeb070029:3301d25c7ed9434688e4f5bd998b9739@sentry.wu2.prague.office-int.com/2"
        },
        "worker": {
            "intelligence": {
                "resume": {
                    "deviceId": "routerlicious",
                    "host": "pkarimov-paidIOT.azure-devices.net",
                    "sharedAccessKeyName": "iothubowner",
                    "sharedAccessKey": "8mvOmNnUklwnuzY+U96V51w+qCq262ZUpSkdw8nTZ18=",
                    "url": "{{ .Values.alfred.externalUrl }}/intelligence/resume"
                },
                "textAnalytics": {
                    "key": "c8b60dc5e49849ce903d7d29a2dce550"
                },
                "nativeTextAnalytics": {
                    "enable": false,
                    "url": "http://praguepy.westus2.cloudapp.azure.com/"
                }
            },
            "alfredUrl": "http://{{ template "alfred.fullname" . }}",
            "serverUrl": "{{ .Values.alfred.externalUrl }}",
            "blobStorageUrl": "{{ .Values.historian.externalUrl }}",
            "repository": "prague",
            "clusterNpm": "https://pragueauspkn-3873244262.azureedge.net",
            "npm": "https://pragueauspkn-3873244262.azureedge.net",
            "permission": ["snapshot", "spell", "intel", "translation", "chain-snapshot", "chain-spell", "chain-intel", "chain-translation"]
        },
    }
