apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{ template "gitrest.fullname" . }}
  labels:
    app: {{ template "routerlicious.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: "{{ .Values.gitrest.name }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/gitrest-configmap.yaml") . | sha256sum }}
      labels:
        app: {{ template "routerlicious.name" . }}
        component: "{{ .Values.gitrest.name }}"
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: {{ template "gitssh.fullname" . }}
        image: "{{ .Values.gitssh.image }}"
        imagePullPolicy: {{ default "" .Values.imagePullPolicy | quote }}
        ports:
        - name: ssh
          containerPort: 22
        volumeMounts:
        - name: data
          mountPath: /home/git
      - name: {{ template "gitrest.fullname" . }}
        image: "{{ .Values.gitrest.image }}"
        imagePullPolicy: {{ default "" .Values.imagePullPolicy | quote }}
        ports:
        - name: http
          containerPort: 3000
        env:
        - name: NODE_ENV
          value: production
        volumeMounts:
        - name: data
          mountPath: /home/node/documents
        - name: config
          mountPath: /home/node/server/config.json
          subPath: config.json
      imagePullSecrets:
      - name: regsecret
      volumes:
        - name: config
          configMap:
            name: {{ template "gitrest.fullname" . }}
        - name: data
          persistentVolumeClaim:
            claimName: {{ .Values.gitrest.persistence.existingClaim | default (include "gitrest.fullname" .) }}

