apiVersion: v1
kind: Service
metadata:
  name: {{ template "gitrest.fullname" . }}
  labels:
    app: {{ template "routerlicious.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: "{{ .Values.gitrest.name }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  ports:
    - name: ssh
      port: 22
      targetPort: ssh
    - name: http
      port: 80
      targetPort: http
  type: LoadBalancer
  selector:
    app: {{ template "routerlicious.name" . }}
    component: "{{ .Values.gitrest.name }}"
    release: {{ .Release.Name }}