{{- if .Values.zookeeper.local }}
apiVersion: v1
kind: Service
metadata:
  name: kafka
  labels:
    app: kafka
spec:
  ports:
    - name: kafka
      port: 9092
  clusterIP: None
  selector:
    app: kafka
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: kafka
spec:
  serviceName: kafka
  replicas: 1
  template:
    metadata:
      labels:
        app: kafka
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: kafka
        image: wurstmeister/kafka:latest
        ports:
        - name: kafka
          containerPort: 9092
        env:
        - name: "KAFKA_ADVERTISED_HOST_NAME"
          value: "kafka-0.kafka.default.svc.cluster.local"
        - name: "KAFKA_ADVERTISED_PORT"
          value: "9092"
        - name: "KAFKA_AUTO_CREATE_TOPICS_ENABLE"
          value: "false"
        - name: "KAFKA_CREATE_TOPICS"
          value: "deltas:8:1,rawdeltas:8:1"
        - name: "KAFKA_ZOOKEEPER_CONNECT"
          value: "zookeeper:2181"
        volumeMounts:
        - name: data
          mountPath: /kafka
  volumeClaimTemplates:
  - metadata:
      name: data
      annotations:
        volume.beta.kubernetes.io/storage-class: ssd
    spec:
      accessModes: 
        - ReadWriteOnce
      resources:
        requests:
          storage: 128Gi
{{- end }}