apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: tmz
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: tmz
    spec:
      containers:
      - name: prague
        image: prague.azurecr.io/prague:local
        command:
          - 'npm'
          - 'run'
          - 'tmz'
        env:
        - name: DEBUG
          value: "routerlicious:*"
        volumeMounts:
        - name: config
          mountPath: /usr/src/server/config.json
          subPath: config.json
      imagePullSecrets:
      - name: regsecret
      volumes:
        - name: config
          configMap:
            name: prague
