version: '2'
services:
    web:
        build: .
        ports:
            - "3000:3000"
        volumes:
            - .:/usr/src/
        depends_on:
            - mongodb
            - redis            
    redis:
        image: "redis:alpine"
    mongodb:
        image: "mongo:3.4.1"