version: '2'
services:
    web:
        build: .
        ports:
            - "3000:3000"
            - "5858:5858"
        volumes:
            - .:/usr/src/
        depends_on:
            - mongodb
            - redis            
        command: node --debug /usr/src/server/dist/www.js
    redis:
        image: "redis:alpine"
    mongodb:
        image: "mongo:3.4.1"
