# Default values for node.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  pullPolicy: IfNotPresent
service:
  name: node
  type: NodePort
  externalPort: 8080
  internalPort: 3000
  host: apps.wu2.prague.office-int.com
  sslCert: wu2-tls-certificate
resources:
  limits:
    cpu: 1024m
    memory: 1024Mi
  requests:
    cpu: 512m
    memory: 512Mi
