version: '3'
services:
    historian:
        build: .
        ports:
            - 3000:3000
            - 5858:5858
        command: node --inspect=0.0.0.0:5858 dist/www.js
    gitrest:
        image: prague.azurecr.io/gitrest:1038
    cobalt:
        image: prague.azurecr.io/cobalt:1544
    redis:
        image: redis:alpine
