version: '3'
services:
    historian:
        build: .
        ports:
            - 3000:3000
        volumes:
            - .:/home/node/server
    gitrest:
        image: prague.azurecr.io/gitrest:629
    redis:
        image: redis:alpine
