apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: gitrest
spec:
  serviceName: gitrest
  replicas: 1
  template:
    metadata:
      labels:
        app: gitrest
    spec:
      containers:
      - name: git
        image: prague.azurecr.io/gitssh:654
        ports:
        - name: ssh
          containerPort: 22
        volumeMounts:
        - name: data
          mountPath: /home/git
      - name: gitrest
        image: prague.azurecr.io/gitrest:653
        ports:
        - name: http
          containerPort: 3000
        env:
        - name: NODE_ENV
          value: production
        volumeMounts:
        - name: data
          mountPath: /home/node/documents
        - name: config
          mountPath: /home/node/server/config.json
          subPath: config.json
      imagePullSecrets:
      - name: regsecret
      volumes:
        - name: config
          configMap:
            name: gitrest
  volumeClaimTemplates:
  - metadata:
      name: data
      annotations:
        volume.beta.kubernetes.io/storage-class: ssd
    spec:
      accessModes: 
        - ReadWriteOnce
      resources:
        requests:
          storage: 128Gi
