apiVersion: v1
kind: ConfigMap
metadata:
  name: historian
data:
  config.json: |
    {
        "logger": {
            "colorize": false,
            "morganFormat": "short",
            "json": false,
            "level": "verbose",
            "timestamp": false
        },
        "requestSizeLimit": "1gb",
        "gitServerUrl": "http://gitrest",
        "redis": {
            "host": "steely-ant-redis",
            "port": 6379
        }
    }