apiVersion: v1
kind: Service
metadata:
  name: historian
  labels:
    app: historian
spec:
  ports:
    - name: http
      port: 80
      targetPort: http
  type: LoadBalancer
  selector:
    app: historian