apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: {{ template "kafka.fullname" . }}
  labels:
    app: {{ template "kafka.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: "kafka"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  serviceName: kafka
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ template "kafka.fullname" . }}
        component: "kafka"
        release: {{ .Release.Name }}
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: kafka
        image: wurstmeister/kafka:latest
        ports:
        - name: kafka
          containerPort: 9092
        env:
        - name: "KAFKA_ADVERTISED_HOST_NAME"
          value: "{{ template "kafka.fullname" . }}-0.{{ template "kafka.fullname" . }}"
        - name: "KAFKA_ADVERTISED_PORT"
          value: "9092"
        - name: "KAFKA_AUTO_CREATE_TOPICS_ENABLE"
          value: "false"
        - name: "KAFKA_CREATE_TOPICS"
          value: "{{ .Values.createTopics }}"
        - name: "KAFKA_ZOOKEEPER_CONNECT"
          value: "{{ template "zookeeper.fullname" .}}:2181"
        volumeMounts:
        - name: data
          mountPath: /kafka
  volumeClaimTemplates:
  - metadata:
      name: data
      annotations:
        volume.beta.kubernetes.io/storage-class: unmanaged-premium
    spec:
      accessModes: 
        - ReadWriteOnce
      resources:
        requests:
          storage: 128Gi
