version: '3'
services:
    delieh:
        build:
            context: ../..
            dockerfile: server/routerlicious/Dockerfile
        ports:
            - "5867:5858"
        command: node --inspect=0.0.0.0:5858 dist/event-hub-service/index.js deli /usr/src/server/packages/server/routerlicious/dist/event-hub/deli/index.js
        environment:
            - DEBUG=prague:*
            - NODE_ENV=development
        volumes:
            - ../../packages:/usr/src/server/packages
        restart: always
    scriptoriumeh:
        build:
            context: ../..
            dockerfile: server/routerlicious/Dockerfile
        command: node dist/event-hub-service/index.js scriptorium /usr/src/server/packages/server/routerlicious/dist/scriptorium/index.js
        environment:
            - DEBUG=prague:*
            - NODE_ENV=development
        volumes:
            - ../../packages:/usr/src/server/packages
        restart: always
    broadcastereh:
        build:
            context: ../..
            dockerfile: server/routerlicious/Dockerfile
        ports:
            - "5868:5858"
        command: node --inspect=0.0.0.0:5858 dist/event-hub-service/index.js broadcaster /usr/src/server/packages/server/routerlicious/dist/broadcaster/index.js
        environment:
            - DEBUG=prague:*
            - NODE_ENV=development
        volumes:
            - ../../packages:/usr/src/server/packages
        restart: always
