kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "cobalt.fullname" . }}
  labels:
    app: {{ template "historian.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: "{{ .Values.cobalt.name }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
  annotations:
    volume.beta.kubernetes.io/storage-class: {{ .Values.cobalt.persistence.storageClass | quote }}
spec:
  accessModes:
    - {{ .Values.cobalt.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.cobalt.persistence.size | quote }}
