kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "gitrest.fullname" . }}
  labels:
    app: {{ template "historian.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: "{{ .Values.gitrest.name }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  storageClassName: managed-premium
  accessModes:
    - {{ .Values.gitrest.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.gitrest.persistence.size | quote }}
