apiVersion: v1
kind: Ingress
metadata:
  name: {{ template "historian.fullname" . }}
  labels:
    app: {{ template "historian.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: "{{ .Values.historian.name }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
  annotations:
    kubernetes.io/ingress.class: "nginx"
    ingress.kubernetes.io/ssl-redirect: "true"
spec:
 tls:
 - hosts:
   - {{ .Values.historian.host }}
   secretName: {{ .Values.historian.cert }}
 rules:
 - host: {{ .Values.historian.host }}
   http:
     paths:
     - path: /
       backend:
         serviceName: {{ template "historian.fullname" . }}
         servicePort: 80