apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "historian.fullname" . }}
  labels:
    app: {{ template "historian.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: "{{ .Values.historian.name }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  config.json: |
    {
        "logger": {
            "colorize": false,
            "morganFormat": "short",
            "json": false,
            "level": "verbose",
            "timestamp": false
        },
        "requestSizeLimit": "1gb",
        "riddler": "{{ .Values.historian.riddler }}",
        "redis": {
            "host": "{{ .Values.historian.redis }}",
            "port": 6379
        }
    }