apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: "{{ .Values.name }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  config.json: |
    {
        "app": {
            "riddlerUrl": "{{ .Values.endpoints.riddlerUrl }}",
            "gitUrl": "{{ .Values.endpoints.gitUrl }}",
            "cobaltUrl": "{{ .Values.endpoints.cobaltUrl }}",
            "historianUrl": "{{ .Values.endpoints.historianUrl }}",
            "alfredUrl": "{{ .Values.endpoints.alfredUrl }}",
            "jarvisUrl": "{{ .Values.endpoints.jarvisUrl }}"
        },
        "login": {
            "microsoft": {
                "clientId": "{{ .Values.login.microsoft.clientId }}",
                "secret": "{{ .Values.login.microsoft.secret }}"
            }
        },
        "logger": {
            "colorize": false,
            "morganFormat": "short",
            "json": true,
            "level": "info",
            "timestamp": true,
            "label": "winston"
        },
        "mongo": {
            "endpoint": "{{ .Values.endpoints.mongodb }}",
            "collectionNames": {
                "tenants": "tenantCollection",
                "users": "userCollection",
                "orgs": "orgCollection"
            }
        },
        "kafka": {
            "lib": {
                "name": "kafka-node",
                "endpoint": "{{ .Values.endpoints.kafka }}"
            }
        },
        "system": {
            "topics": {
                "send": "deltas"
            }
        },
        "error": {
            "track": true,
            "endpoint" : "{{ .Values.error.endpoint }}"
        },
        "redis": {
            "host": "{{ .Values.endpoints.redis }}",
            "port": 6379
        },
        "loader": {
            "orderer": "https://alfred.wu2.prague.office-int.com",
            "storage": "https://historian.wu2.prague.office-int.com",
            "tenant": "dreamy-jang",
            "secret": "70fe794a484bebbfa2b0813745a4450e",
            "jwtKey": "VBQyoGpEYrTn3XQPtXW3K8fFDd",
            "documentId": "key-value-manager-0001",
            "package": "@chaincode/key-value@0.3.6901"
        },
        "express": {
            "session": {
                "secret": {{ .Values.express.session.secret }}
            }
        }
    }