apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: "{{ .Values.name }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  config.json: |
    {
        "app": {
            "logger": {
                "colorize": true,
                "morganFormat": "dev",
                "json": false,
                "level": "info",
                "timestamp": true,
                "label": "winston"
            },
            "port": 3000,
            "tenantInfo": {
                "id": "{{ .Values.tenantId }}",
                "secretKey": "{{ .Values.secretKey }}",
                "endpoints": {
                    "delta": "{{ .Values.endpoints.delta }}",
                    "storage": "{{ .Values.endpoints.storage }}"
                }
            },
            "worker": {
                "intelligence": {
                    "resume": {
                        "deviceId": "routerlicious",
                        "host": "pkarimov-paidIOT.azure-devices.net",
                        "sharedAccessKeyName": "iothubowner",
                        "sharedAccessKey": "8mvOmNnUklwnuzY+U96V51w+qCq262ZUpSkdw8nTZ18=",
                        "url": "{{ .Values.endpoints.resume }}"
                    },
                    "textAnalytics": {
                        "key": "c8b60dc5e49849ce903d7d29a2dce550"
                    },
                    "nativeTextAnalytics": {
                        "enable": false,
                        "url": "{{ .Values.endpoints.nativeTextAnalytics }}"
                    }
                },
                "alfredUrl": "{{ .Values.endpoints.serverUrl }}",
                "serverUrl": "{{ .Values.endpoints.serverUrl }}",
                "blobStorageUrl": "{{ .Values.endpoints.blobStorageUrl }}",
                "repository": "prague",
                "permission": ["snapshot", "spell", "intel", "translation"]
            }
        },
        "aad": {
            "creds": {
                "identityMetadata": "https://login.microsoftonline.com/microsoft.onmicrosoft.com/.well-known/openid-configuration",
                "clientID": "3d642166-9884-4463-8248-78961b8c1300",
                "responseType": "code id_token",
                "responseMode": "form_post",
                "redirectUrl": "{{ .Values.auth.redirectUrl }}",
                "allowHttpForRedirectUrl": true,
                "clientSecret": "IefegJIsumWtD1Of/9AIUWvm6ryR624vgMtKRmcNEsQ=",
                "validateIssuer": true,
                "isB2C": false,
                "issuer": null,
                "passReqToCallback": false,
                "useCookieInsteadOfSession": true,
                "cookieEncryptionKeys": [
                  { "key": "12345678901234567890123456789012", "iv": "123456789012" },
                  { "key": "abcdefghijklmnopqrstuvwxyzabcdef", "iv": "abcdefghijkl" }
                ],
                "scope": ["email", "profile"],
                "loggingLevel": "info",
                "nonceLifetime": null,
                "nonceMaxAmount": 5,
                "clockSkew": null
            },
            "resourceURL": "https://graph.windows.net",
            "destroySessionUrl": "{{ .Values.auth.destroySessionUrl }}",
            "useMongoDBSessionStore": false,
            "databaseUri": null,
            "mongoDBSessionMaxAge": 14400
        }
    }