apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: alfred
spec:
  replicas: 4
  template:
    metadata:
      labels:
        app: alfred
    spec:
      containers:
      - name: routerlicious
        image: prague.azurecr.io/prague:443
        ports:
        - name: ui
          containerPort: 3000
        env:
        - name: logger__colorize
          value: "false"
        - name: logger__morganFormat
          value: combined
        - name: logger__json
          value: "false"
        - name: logger__level
          value: verbose
        - name: logger__timestamp
          value: "false"
        - name: DEBUG
          value: "routerlicious:*"
        - name: minio__endpoint
          value: minio-service
        - name: minio__accessKey
          value: prague
        - name: minio__secretKey
          value: mhioAkNXTwdX4dXWgKgXVtHo
        - name: zookeeper__endpoint
          value: "zookeeper:2181"
        - name: redis__host
          value: "redis"
        - name: mongo__endpoint
          value: "mongodb://mongodb:27017"
      imagePullSecrets:
      - name: regsecret
---
apiVersion: v1
kind: Service
metadata:
  name: alfred
  labels:
    app: alfred
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
    targetPort: ui
  selector:
    app: alfred
