apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: kafka-prague
spec:
  serviceName: kafka-prague
  replicas: 1
  template:
    metadata:
      labels:
        app: kafka-prague
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: kafka-prague
        # Pulls the default Minio image from Docker Hub
        image: wurstmeister/kafka
        ports:
        - name: kafka-prague
          containerPort: 9092
        env:
        - name: "KAFKA_ADVERTISED_HOST_NAME"
          value: "kfka"
        - name: "KAFKA_ADVERTISED_PORT"
          value: "9092"
        - name: "KAFKA_AUTO_CREATE_TOPICS_ENABLE"
          value: "false"
        - name: "KAFKA_CREATE_TOPICS"
          value: "deltas:8:1,rawdeltas:8:1"
        - name: "KAFKA_ZOOKEEPER_CONNECT"
          value: "zookeeper:2181"
        volumeMounts:
        - name: data
          mountPath: /kafka
  volumeClaimTemplates:
  - metadata:
      name: data
      annotations:
        volume.alpha.kubernetes.io/storage-class: anything
    spec:
      accessModes: 
        - ReadWriteOnce
      resources:
        requests:
          storage: 50Gi
---
apiVersion: v1
kind: Service
metadata:
  name: kfka
spec:
  ports:
    - name: kafka
      port: 9092
  selector:
    app: kafka-prague
