apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  # This name uniquely identifies the Deployment
  name: mongodb
spec:
  template:
    metadata:
      labels:
        # Label is used as selector in the service.
        app: mongodb
    spec:
      containers:
      - name: mongodb
        # Pulls the default Minio image from Docker Hub
        image: mongo:3.4.3
        ports:
        - name: mongodb
          containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
spec:
  ports:
    - name: mongodb
      port: 27017
      targetPort: mongodb
  selector:
    app: mongodb