apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: "{{ .Values.name }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  config.json: |
    {
        "app": {
            "riddlerUrl": "{{ .Values.endpoints.riddlerUrl }}",
            "gitUrl": "{{ .Values.endpoints.gitUrl }}",
            "cobaltUrl": "{{ .Values.endpoints.cobaltUrl }}"
        },
        "login": {
            "microsoft": {
                "clientId": "3d642166-9884-4463-8248-78961b8c1300",
                "secret": "IefegJIsumWtD1Of/9AIUWvm6ryR624vgMtKRmcNEsQ="
            }
        },
        "logger": {
            "colorize": true,
            "morganFormat": "dev",
            "json": false,
            "level": "info",
            "timestamp": true,
            "label": "winston"
        },
        "mongo": {
            "endpoint": "{{ .Values.endpoints.mongodb }}",
            "collectionNames": {
                "tenants": "tenantCollection",
                "users": "userCollection",
                "orgs": "orgCollection"
            }
        },
        "kafka": {
            "lib": {
                "name": "kafka-node",
                "endpoint": "{{ .Values.endpoints.kafka }}"
            }
        },
        "system": {
            "topics": {
                "send": "deltas"
            }
        },
        "error": {
            "track": true,
            "endpoint" : "https://344cbdea481f46baa1d3f5144c90b1f6:0385ef41b1444e8ebff49c9a6b647485@sentry.wu2.prague.office-int.com/3"
        },
        "redis": {
            "host": "{{ .Values.endpoints.redis }}",
            "port": 6379
        }
    }