apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: "{{ .Values.name }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  config.json: |
    {
        "app": {
            "logger": {
                "colorize": true,
                "morganFormat": "dev",
                "json": false,
                "level": "info",
                "timestamp": true,
                "label": "winston"
            },
            "mongo": {
                "endpoint": "{{ .Values.endpoints.mongodb }}",
                "collectionNames": {
                    "tenants": "tenants"
                }
            },
            "endpoints": {
                "tenantsUrl": "{{ .Values.endpoints.tenantsUrl }}"
            },
            "port": 3000,
            "tenantConfig": [
                {
                    "name": "git",
                    "storage": {
                        "url": "{{ .Values.endpoints.historianUrl }}",
                        "publicUrl": "{{ .Values.endpoints.historianUrl }}",
                        "owner": "prague",
                        "repository": "prague"
                    },
                    "isDefault": true
                },
                {
                    "name": "github",
                    "storage": {
                        "url": "{{ .Values.endpoints.historianUrl }}/github",
                        "publicUrl": "{{ .Values.endpoints.historianUrl }}/github",
                        "owner": "kurtb",
                        "repository": "praguedocs",
                        "direct": "https://api.github.com",
                        "credentials": {
                            "user": "praguegit",
                            "password": "8d043006d0a2704d4dd9972f848f1982026672a1"
                        }
                    }
                },
                {
                    "name": "cobalt",
                    "storage": {
                        "url": "{{ .Values.endpoints.historianUrl }}/cobalt",
                        "publicUrl": "{{ .Values.endpoints.historianUrl }}/cobalt",
                        "owner": "prague",
                        "repository": "prague"
                    }
                }
            ]
        },
        "aad": {
            "creds": {
                "identityMetadata": "https://login.microsoftonline.com/microsoft.onmicrosoft.com/.well-known/openid-configuration",
                "clientID": "3d642166-9884-4463-8248-78961b8c1300",
                "responseType": "code id_token",
                "responseMode": "form_post",
                "redirectUrl": "{{ .Values.auth.redirectUrl }}",
                "allowHttpForRedirectUrl": true,
                "clientSecret": "IefegJIsumWtD1Of/9AIUWvm6ryR624vgMtKRmcNEsQ=",
                "validateIssuer": true,
                "isB2C": false,
                "issuer": null,
                "passReqToCallback": false,
                "useCookieInsteadOfSession": true,
                "cookieEncryptionKeys": [
                  { "key": "12345678901234567890123456789012", "iv": "123456789012" },
                  { "key": "abcdefghijklmnopqrstuvwxyzabcdef", "iv": "abcdefghijkl" }
                ],
                "scope": ["email", "profile"],
                "loggingLevel": "info",
                "nonceLifetime": null,
                "nonceMaxAmount": 5,
                "clockSkew": null
            },
            "resourceURL": "https://graph.windows.net",
            "destroySessionUrl": "{{ .Values.auth.destroySessionUrl }}",
            "useMongoDBSessionStore": false,
            "databaseUri": null,
            "mongoDBSessionMaxAge": 14400
        }
    }