kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "gitrest.fullname" . }}
  labels:
    app: {{ template "historian.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: "{{ .Values.gitrest.name }}"
    release: "{{ .Release.Name }}"
  {{ if and .Values.gitrest.mode (eq .Values.gitrest.mode "legacy") }}
    annotations:
      volume.beta.kubernetes.io/storage-class: {{ .Values.gitrest.persistence.storageClass | quote }}
  {{ end }}
spec:
  {{ if and .Values.gitrest.mode (eq .Values.gitrest.mode "latest") }}
    storageClassName: managed-premium
  {{ end }}
  accessModes:
    - {{ .Values.gitrest.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.gitrest.persistence.size | quote }}
