kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: azure-premium
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: kubernetes.io/azure-disk
parameters:
  skuName: Premium_LRS
  location: westus2
