kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: azure-standard
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: kubernetes.io/azure-disk
parameters:
  skuName: Standard_LRS
  location: westus2
  storageAccount: praguekubestandardsc