version: '3'
services:
    augloop:
        build: .
        command: node dist/index.js
        environment:
            - DEBUG=augloop:*
            - NODE_ENV=development
        restart: always
        volumes:
            - .:/usr/src/server
        networks:
            - routerlicious_default

networks:
    routerlicious_default:
        external: true