version: '3'
services:
    perf:
      build: . 
      ports:
            - "5858:5858"
            - "5859:5859"
      depends_on:
            - kafka
      command: npm run perf:kafka:debug
      volumes:
            - .:/usr/src/server
      restart: always
    zookeeper:
        image: wurstmeister/zookeeper
        ports:
            - "2181:2181"
    kafka:
        image: wurstmeister/kafka
        depends_on:
            - zookeeper
        ports:
            - "9092:9092"
        environment:
            KAFKA_ADVERTISED_HOST_NAME: "kafka"
            KAFKA_ADVERTISED_PORT: "9092"
            KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'false'
            KAFKA_CREATE_TOPICS: "test:1:1,deltas:8:1,rawdeltas:8:1"
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
