version: '3'
services:
    perf:
      build: . 
      ports:
            - "5858:5858"
      depends_on:
            - redis
            - mongodb
            - kafka-rest
      command: npm run perf:scriptorium:debug
      volumes:
            - .:/usr/src/server
      restart: always
    scriptorium:
      build: .
      ports:
            - "5859:5858"
      depends_on:
            - redis
            - mongodb
            - kafka-rest
      command: npm run scriptorium:debug
      volumes:
            - .:/usr/src/server
      restart: always

    zookeeper:
        image: wurstmeister/zookeeper:latest
        hostname: zookeeper
        ports:
            - "2181:2181"

    kafka:
        image: wurstmeister/kafka:latest
        hostname: kafka
        depends_on:
            - zookeeper
        ports:
            - "9092:9092"
        environment:
            KAFKA_ADVERTISED_HOST_NAME: "kafka"
            KAFKA_ADVERTISED_PORT: "9092"
            KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'false'
            KAFKA_CREATE_TOPICS: "deltas:8:1,rawdeltas:8:1"
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

    kafka-rest:
        image: confluentinc/cp-kafka-rest:latest
        hostname: kafka-rest
        depends_on:
            - zookeeper
            - kafka
        ports:
            - "8082:8082"
        environment:
            KAFKA_REST_ZOOKEEPER_CONNECT: 'zookeeper:2181'
            KAFKA_REST_LISTENERS: http://kafka-rest:8082
            KAFKA_REST_HOST_NAME: kafka-rest
            
    redis:
        image: "redis:alpine"
    mongodb:
        image: "mongo:3.4.3"
    rabbitmq:
        image: "rabbitmq:alpine"
    minio:
        image: minio/minio
        ports:
            - "9000:9000"
        environment:
            MINIO_ACCESS_KEY: prague
            MINIO_SECRET_KEY: mhioAkNXTwdX4dXWgKgXVtHo
        command: server /export