version: '2'
services:
    web:
        build: .
        ports:
            - "3000:3000"
        volumes:
            - .:/usr/src/server
        depends_on:
            - redis
    deli:
        build: .
        volumes:
            - .:/usr/src/server
        depends_on:
            - redis
        command: npm run deli
    redis:
        image: "redis:alpine"
