version: '3'
services:
    alfred:
        build: .
        ports:
            - "3000:3000"
        depends_on:
            - redis
            - mongodb
            - kafka-rest
        command: npm run alfred
        environment:
            - DEBUG=routerlicious:*
        restart: always
    deli:
        build: .
        depends_on:
            - redis
            - mongodb
            - kafka-rest
        command: npm run deli
        environment:
            - DEBUG=routerlicious:*
        restart: always
    paparazzi:
        build: .
        depends_on:
            - alfred
            - rabbitmq
        command: npm run paparazzi
        environment:
            - DEBUG=routerlicious:*
            - worker__intelligence__resume__url=http://alfred:3000/intelligence/resume
        restart: always
    scriptorium:
        build: .
        depends_on:
            - redis
            - mongodb
            - kafka-rest
        command: npm run scriptorium
        environment:
            - DEBUG=routerlicious:*
        restart: always
    tmz:
        build: .
        ports:
            - "4000:4000"
        depends_on:
            - redis
            - mongodb
            - rabbitmq
            - kafka-rest
        command: npm run tmz
        environment:
            - DEBUG=routerlicious:*
        restart: always
    historian:
        image: prague.azurecr.io/historian:591
        ports:
            - "3001:3000"
        environment:
            - DEBUG=routerlicious:*
        volumes:
            - git:/home/node/documents
        restart: always
    git:
        image: prague.azurecr.io/gitssh:552
        ports:
            - "3022:22"
        volumes:
            - git:/home/git
    zookeeper:
        image: wurstmeister/zookeeper:latest
        ports:
            - "2181:2181"
    kafka:
        image: wurstmeister/kafka:latest
        depends_on:
            - zookeeper
        ports:
            - "9092:9092"
        environment:
            KAFKA_ADVERTISED_HOST_NAME: "kafka"
            KAFKA_ADVERTISED_PORT: "9092"
            KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'false'
            KAFKA_CREATE_TOPICS: "deltas:8:1,rawdeltas:8:1"
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    kafka-rest:
        image: confluentinc/cp-kafka-rest:latest
        depends_on:
            - zookeeper
            - kafka
        ports:
            - "8082:8082"
        logging:
            driver: none
        environment:
            KAFKA_REST_ZOOKEEPER_CONNECT: 'zookeeper:2181'
            KAFKA_REST_LISTENERS: http://kafka-rest:8082
            KAFKA_REST_HOST_NAME: kafka-rest
            KAFKA_REST_CONSUMER_REQUEST_TIMEOUT_MS: 1
    redis:
        image: "redis:alpine"
    mongodb:
        image: "mongo:3.4.3"
    rabbitmq:
        image: "rabbitmq:alpine"
    minio:
        image: minio/minio
        ports:
            - "9000:9000"
        environment:
            MINIO_ACCESS_KEY: prague
            MINIO_SECRET_KEY: mhioAkNXTwdX4dXWgKgXVtHo
        command: server /export
volumes:
  git:
    driver: local