version: '2'
services:
    web:
        build: .
        ports:
            - "3000:3000"
        volumes:
            - .:/usr/src/server
        depends_on:
            - redis
    deli:
        build: .
        volumes:
            - .:/usr/src/server
        depends_on:
            - redis
        command: npm run deli
    paparazzi:
        build: .
        volumes:
            - .:/usr/src/server
        depends_on:
            - redis
            - web
        command: npm run paparazzi
    scriptorium:
        build: .
        volumes:
            - .:/usr/src/server
        depends_on:
            - redis
        command: npm run scriptorium
    tmz:
        build: .
        volumes:
            - .:/usr/src/server
        depends_on:
            - redis
        command: npm run tmz
    redis:
        image: "redis:alpine"
