version: '3'
services:
    web:
        image: 127.0.0.1:5000/routerlicious
        build: .
        ports:
            - "3000:3000"
        depends_on:
            - redis
            - mongodb
            - kafka
    deli:
        image: 127.0.0.1:5000/routerlicious
        build: .
        depends_on:
            - redis
            - mongodb
            - kafka
        command: npm run deli
    paparazzi:
        image: 127.0.0.1:5000/routerlicious
        build: .
        depends_on:
            - web
            - rabbitmq
        command: npm run paparazzi
    scriptorium:
        image: 127.0.0.1:5000/routerlicious
        build: .
        depends_on:
            - redis
            - mongodb
            - kafka
        command: npm run scriptorium
    tmz:
        image: 127.0.0.1:5000/routerlicious
        build: .
        depends_on:
            - redis
            - mongodb
            - rabbitmq
            - kafka
        command: npm run tmz
    zookeeper:
        image: wurstmeister/zookeeper
        ports:
            - "2181:2181"
    kafka:
        image: wurstmeister/kafka
        depends_on:
            - zookeeper
        ports:
            - "9092:9092"
        environment:
            KAFKA_ADVERTISED_HOST_NAME: "kafka"
            KAFKA_ADVERTISED_PORT: "9092"
            KAFKA_CREATE_TOPICS: "test:1:1,deltas:8:1,rawdeltas:8:1"
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    redis:
        image: "redis:alpine"
    mongodb:
        image: "mongo:3.4.3"
    rabbitmq:
        image: "rabbitmq:alpine"
    minio:
        image: minio/minio
        ports:
            - "9000:9000"
        environment:
            MINIO_ACCESS_KEY: prague
            MINIO_SECRET_KEY: mhioAkNXTwdX4dXWgKgXVtHo
        command: server /export
    elasticsearch:
        image: elasticsearch:latest
        ports:
            - "9200:9200"
            - "9300:9300"
        #volume-driver: flocker
        volumes:
            - ./elasticsearch/data:/usr/share/elasticsearch/data
    logstash:
        image: logstash:latest
        command: logstash -f /etc/logstash/conf.d/logstash.conf
        volumes:
            - ./logstash.conf:/etc/logstash/conf.d/logstash.conf
        ports:
            - "5000:5000"
        links:
            - elasticsearch
    kibana:
        image: kibana
        ports:
            - "5601:5601"
        links:
            - elasticsearch

#volumes:
#  elasticsearch1:
