version: '3'
services:
    alfred:
        ports:
            - "5858:5858"
        command: node --inspect=0.0.0.0:5858 dist/alfred/www.js
    deli:
        ports:
            - "5859:5858"
        command: node --inspect=0.0.0.0:5858 dist/kafka-service/index.js deli /usr/src/server/packages/server/routerlicious/dist/deli/index.js
    paparazzi:
        ports:
            - "5860:5858"
        command: node --inspect=0.0.0.0:5858 dist/paparazzi/index.js
    scriptorium:
        ports:
            - "5861:5858"
        command: node --inspect=0.0.0.0:5858 dist/kafka-service/index.js scriptorium /usr/src/server/packages/server/routerlicious/dist/scriptorium/index.js
    bbc:
        ports:
            - "5865:5858"
        command: node --inspect=0.0.0.0:5858 dist/kafka-service/index.js bbc /usr/src/server/packages/server/routerlicious/dist/bbc/index.js
    tmz:
        ports:
            - "5862:5858"
        command: node --inspect=0.0.0.0:5858 dist/kafka-service/index.js tmz /usr/src/server/packages/server/routerlicious/dist/tmz/index.js
    routemaster:
        ports:
            - "5863:5858"
        command: node --inspect=0.0.0.0:5858 dist/kafka-service/index.js routemaster /usr/src/server/packages/lambdas-driver/dist/document-router/index.js
    rotograph:
        ports:
            - "5864:5858"
        command: node --inspect=0.0.0.0:5858 dist/kafka-service/index.js rotograph /usr/src/server/packages/server/routerlicious/dist/rotograph/index.js