version: '3'
services:
    alfred:
        depends_on:
            - logstash
        logging:
            driver: gelf
            options:
                gelf-address: "udp://127.0.0.1:12201"
                tag: "log-alfred"
    deli:
        depends_on:
            - logstash
        logging:
            driver: gelf
            options:
                gelf-address: "udp://127.0.0.1:12201"
                tag: "log-deli"
    paparazzi:
        depends_on:
            - logstash
        logging:
            driver: gelf
            options:
                gelf-address: "udp://127.0.0.1:12201"
                tag: "log-paparazzi"
    scriptorium:
        depends_on:
            - logstash
        logging:
            driver: gelf
            options:
                gelf-address: "udp://127.0.0.1:12201"
                tag: "log-scriptorium"
    tmz:
        depends_on:
            - logstash
        logging:
            driver: gelf
            options:
                gelf-address: "udp://127.0.0.1:12201"
                tag: "log-tmz"
    elasticsearch:
        image: elasticsearch:latest
        ports:
            - "9200:9200"
            - "9300:9300"
        volumes:
            - esdata:/usr/share/elasticsearch/data
        environment:
            - http.host=0.0.0.0
    logstash:
        image: logstash:latest
        command: logstash -e 'input { gelf { type => docker port => 12201 } } output { elasticsearch { hosts => "elasticsearch:9200" } stdout {  codec => rubydebug } }'
        expose:
            - "12201"
        ports:
            - "12201:12201"
            - "12201:12201/udp"
        links:
            - elasticsearch
    kibana:
        image: kibana
        ports:
            - "5601:5601"
        links:
            - elasticsearch
    elastalert:
        image: ivankrizsan/elastalert:latest
        depends_on:
            - elasticsearch
            - kibana
        volumes:
          - elastalertlogs:/opt/logs
          - ./config/elastalert/rules:/opt/rules
          - ./config/elastalert/config:/opt/config
        links:
            - elasticsearch:elasticsearchhost    


volumes:
  esdata:
    driver: local
  elastalertlogs:
    driver: local
