version: '2'
services:
    web:
        build: .
        ports:
            - "3000:3000"
        volumes:
            - .:/usr/src/server
        depends_on:
            - redis
            - mongodb
    deli:
        build: .
        volumes:
            - .:/usr/src/server
        depends_on:
            - redis
            - mongodb
        command: npm run deli
    paparazzi:
        build: .
        volumes:
            - .:/usr/src/server
        depends_on:
            - web
            - rabbitmq
        command: npm run paparazzi
    scriptorium:
        build: .
        volumes:
            - .:/usr/src/server
        depends_on:
            - redis
            - mongodb
        command: npm run scriptorium
    tmz:
        build: .
        volumes:
            - .:/usr/src/server
        depends_on:
            - redis
            - mongodb
            - rabbitmq
        command: npm run tmz
    redis:
        image: "redis:alpine"
    mongodb:
        image: "mongo:3.4.3"
    rabbitmq:
        image: "rabbitmq:alpine"
