version: '3'
services:
    gateway:
        volumes:
            - .:/usr/src/server
    alfred:
        volumes:
            - .:/usr/src/server
    deli:
        volumes:
            - .:/usr/src/server
    delieh:
        volumes:
            - .:/usr/src/server
    scriptoriumeh:
        volumes:
            - .:/usr/src/server
    bbceh:
        volumes:
            - .:/usr/src/server
    scriptorium:
        volumes:
            - .:/usr/src/server
    bbc:
        volumes:
            - .:/usr/src/server
    tmz:
        volumes:
            - .:/usr/src/server
    paparazzi:
        volumes:
            - .:/usr/src/server
    routemaster:
        volumes:
            - .:/usr/src/server
    riddler:
        volumes:
            - .:/usr/src/server
