version: '3'
services:
    alfred:
        volumes:
            - .:/usr/src/server
    deli:
        volumes:
            - .:/usr/src/server
    scriptorium:
        volumes:
            - .:/usr/src/server
    tmz:
        volumes:
            - .:/usr/src/server
    rotograph:
        volumes:
            - .:/usr/src/server
    paparazzi:
        volumes:
            - .:/usr/src/server
    routemaster:
        volumes:
            - .:/usr/src/server
    riddler:
        volumes:
            - .:/usr/src/server
