apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: intelligence
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: intelligence
    spec:
      containers:
      - name: intelligence
        image: prague.azurecr.io/intelligence:526
        command:
          - 'python'
          - 'text-analytics/server.py'
        ports:
        - name: ui
          containerPort: 8080
      imagePullSecrets:
      - name: regsecret
---
apiVersion: v1
kind: Service
metadata:
  name: intelligence
  labels:
    app: intelligence
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
    targetPort: ui
  selector:
    app: intelligence
