apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "metrics.fullname" . }}
  labels:
    app: {{ template "metrics.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: "{{ .Values.name }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  config.json: |
    {
        "logger": {
            "colorize": false,
            "morganFormat": "short",
            "json": false,
            "level": "verbose",
            "timestamp": false
        },
        "system": {
            "topics": {
                "send": "{{ .Values.kafka.sendTopic }}"
            }
        },
        "kafka": {
            "lib": {
                "name": "kafka-node",
                "endpoint": "{{ .Values.kafka.zookeeper }}"
            }
        },
        "error": {
            "track": true,
            "endpoint" : "{{ .Values.sentry }}"
        },
        "lambdas": {
            "prague-metrics": {
                "group": "{{ .Values.kafka.group }}",
                "topic": "{{ .Values.kafka.receiveTopic }}"
            }
        },
        "tenantId": "{{ .Values.aria.tenant }}",
        "eventName": "{{ .Values.aria.event }}",
        "environment": "{{ .Values.environment }}"
    }