apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "routerlicious.fullname" . }}
  labels:
    app: {{ template "routerlicious.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: "{{ .Values.name }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  config.json: |
    {
        "logger": {
            "colorize": false,
            "morganFormat": "short",
            "json": true,
            "level": "info",
            "timestamp": false,
            "label": "winston"
        },
        "mongo": {
            "endpoint": "{{ .Values.mongodb.url }}",
            "collectionNames": {
                "deltas": "deltas",
                "documents": "documents",
                "partitions": "partitions",
                "tenants": "tenants",
                "nodes": "nodes",
                "reservations": "reservations"
            }
        },
        "kafka": {
            "endpoint": "{{ .Values.kafka.url }}:9092",
            "lib": {
                "name": "kafka-node",
                "endpoint": "{{ .Values.zookeeper.url }}"
            },
            "maxMessageSize": "1MB"
        },
        "alfred": {
            "kafkaClientId": "{{ template "jarvis.fullname" . }}",
            "maxMessageSize": "16KB",
            "topic": "{{ .Values.kafka.topics.rawdeltas }}",
            "bucket": "snapshots",
            "restJsonSize": "50mb",
            "tenants": [
                {{- range $index, $tenant := .Values.jarvis.tenants }}
                {{ toJson . }},
                {{- end }}
                {
                    "id": "prague",
                    "key": "43cfc3fbf04a97c0921fd23ff10f9e4b"
                },
                {
                    "id": "github",
                    "key": "0bea3f87c186991a69245a29dc3f61d2"
                },
                {
                    "id": "cobalt",
                    "key": "0e3c439e9ba63d85936c7e7e9c79478c"
                },
                {
                    "id": "local",
                    "key": "43cfc3fbf04a97c0921fd23ff10f9e4b"
                }
            ]
        },
        "client": {
            "type": "browser",
            "permission": []
        },
        "login": {
            "enabled": true,
            "microsoft": {
                "clientId": "",
                "secret": ""
            },
            "accounts": [
                {
                    "username": "",
                    "password": ""
                }
            ]
        },
        "deli": {
            "topics": {
                "receive": "{{ .Values.kafka.topics.rawdeltas }}",
                "send": "{{ .Values.kafka.topics.deltas }}"
            },
            "kafkaClientId": "{{ template "deli.fullname" . }}",
            "groupId": "{{ template "deli.fullname" . }}",
            "checkpointBatchSize": 10,
            "checkpointTimeIntervalMsec": 1000
        },
        "foreman": {
            "queues": ["paparazziQueue2", "augloopQueue2"],
            "permissions": {
                "paparazziQueue": ["snapshot", "spell", "intel", "translation", "chain-snapshot", "chain-spell", "chain-intel", "chain-translation"],
                "augloopQueue": ["augmentation"]
            }
        },
        "system": {
            "topics": {
                "send": "{{ .Values.kafka.topics.deltas }}"
            }
        },
        "auth": {
            "endpoint": "{{ .Values.riddler.url }}"
        },
        "lambdas": {
            "deli": {
                "group": "{{ template "deli.fullname" . }}",
                "topic": "{{ .Values.kafka.topics.rawdeltas }}"
            },
            "scriptorium": {
                "group": "{{ template "scriptorium.fullname" . }}",
                "topic": "{{ .Values.kafka.topics.deltas }}"
            },
            "broadcaster": {
                "group": "{{ template "broadcaster.fullname" . }}",
                "topic": "{{ .Values.kafka.topics.deltas }}"
            }
        },
        "scriptorium": {
            "topic": "{{ .Values.kafka.topics.deltas }}",
            "kafkaClientId": "{{ template "scriptorium.fullname" . }}",
            "groupId": "{{ template "scriptorium.fullname" . }}",
            "checkpointBatchSize": 1,
            "checkpointTimeIntervalMsec": 1000
        },
        "rabbitmq": {
            "connectionString": "{{ .Values.rabbitmq.connectionString }}"
        },
        "redis": {
            "host": "{{ .Values.redis.url }}",
            "port": 6379
        },
        "error": {
            "track": true,
            "endpoint" : ""
        },
        "worker": {
            "intelligence": {
                "resume": {
                },
                "textAnalytics": {
                    "key": ""
                },
                "nativeTextAnalytics": {
                },
                "translation": {
                    "key": ""
                }
            },
            "alfredUrl": "http://{{ template "jarvis.fullname" . }}",
            "serverUrl": "{{ .Values.jarvis.externalUrl }}",
            "blobStorageUrl": "{{ .Values.historian.externalUrl }}",
            "repository": "prague",
            "npm": "",
            "permission": ["snapshot", "spell", "intel", "translation", "chain-snapshot", "chain-spell", "chain-intel", "chain-translation"]
        },
        "tenantConfig": [
            {
                "_id": "prague",
                "key": "43cfc3fbf04a97c0921fd23ff10f9e4b",
                "storage": {
                    "url": "{{ .Values.gitrest.url }}",
                    "owner": "prague",
                    "repository": "prague"
                }
            },
            {
                "_id": "github",
                "key": "0bea3f87c186991a69245a29dc3f61d2",
                "storage": {
                    "url": "https://api.github.com",
                    "owner": "kurtb",
                    "repository": "praguedocs",
                    "direct": "https://api.github.com",
                    "credentials": {
                        "user": "",
                        "password": ""
                    }
                }
            },
            {
                "_id": "cobalt",
                "key": "0e3c439e9ba63d85936c7e7e9c79478c",
                "storage": {
                    "url": "{{ .Values.cobalt.url }}",
                    "owner": "prague",
                    "repository": "prague"
                }
            },
            {
                "_id": "local",
                "key": "43cfc3fbf04a97c0921fd23ff10f9e4b",
                "storage": {
                    "url": "{{ .Values.gitrest.url }}",
                    "owner": "prague",
                    "repository": "local"
                }
            }
        ],
        "metric": {
            "client": "telegraf",
            "telegraf": {
                "host": "polling-telegraf-service.metric",
                "port": 8094
            }
        },
        "minio": {
            "endpoint": "{{ .Values.minio.endpoint }}",
            "port": 9000,
            "accessKey": "",
            "secretKey": "",
            "bucket": "agents"
        }
    }
