version: '3'
services:
    apps:
        build: .
        ports:
            - "7000:3000"
        command: node dist/www.js
        volumes:
            - .:/usr/src/server
        networks:
            - routerlicious_default

networks:
    routerlicious_default:
        external: true