version: '3'
services:
    apps:
        build: .
        ports:
            - "7000:3000"
        command: node dist/www.js
        volumes:
            - .:/usr/src/server
    mongodb:
        image: "mongo:3.4.3"