apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: elastalert
spec:
  serviceName: elastalert
  replicas: 1
  template:
    metadata:
      labels:
        app: elastalert
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: elastalert
        image: ivankrizsan/elastalert:latest
        volumeMounts:
        - name: logs
          mountPath: /opt/logs
        - name: rules
          mountPath: /opt/rules
        - name: config
          mountPath: /opt/config

      volumes:
      - name: rules
        hostPath:
          path: /config/elastalert/rules
      - name: config
        hostPath:
          path: /config/elastalert/config

  volumeClaimTemplates:
  - metadata:
      name: logs
      annotations:
        volume.alpha.kubernetes.io/storage-class: anything
    spec:
      accessModes: 
        - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi  
