apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  # This name uniquely identifies the Deployment
  name: rabbitmq
spec:
  template:
    metadata:
      labels:
        # Label is used as selector in the service.
        app: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        # Pulls the default Minio image from Docker Hub
        image: rabbitmq:alpine
        ports:
        - name: epmd
          containerPort: 4369
        - name: ampq
          containerPort: 5671
        - name: dist
          containerPort: 5672
        - name: stats
          containerPort: 25672
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
spec:
  ports:
    - name: epmd
      port: 4369
    - name: ampq
      port: 5671
    - name: dist
      port: 5672
    - name: stats
      port: 25672
  selector:
    app: rabbitmq