apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  # This name uniquely identifies the Deployment
  name: redis
spec:
  template:
    metadata:
      labels:
        # Label is used as selector in the service.
        app: redis
    spec:
      containers:
      - name: redis
        # Pulls the default Minio image from Docker Hub
        image: redis:alpine
        ports:
        - name: redis
          containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  ports:
    - name: redis
      port: 6379
      targetPort: redis
  selector:
    app: redis