apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: walkout
  labels:
    app: walkout
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: walkout
    spec:
      containers:
      - name: walkout
        image: prague.azurecr.io/walkout:0.2
        imagePullPolicy: IfNotPresent
        ports:
        - name: ui
          containerPort: 3000
        env:
        - name: DEBUG
          value: "routerlicious:*"
        - name: NODE_ENV
          value: production
      imagePullSecrets:
      - name: regsecret
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: walkout
  labels:
    app: walkout
  annotations:
    kubernetes.io/ingress.class: nginx-prod
spec:
  tls:
  - hosts:
    - walkout.eu.prague.office-int.com
    secretName: eu-tls-certificate
  rules:
  - host: walkout.eu.prague.office-int.com
    http:
      paths:
      - path: /
        backend:
          serviceName: walkout
          servicePort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: walkout
  labels:
    app: walkout
spec:
  type: ClusterIP
  ports:
  - port: 80
    protocol: TCP
    targetPort: ui
  selector:
    app: walkout
