apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: augmentation
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: augmentation
    spec:
      containers:
      - name: augmentation
        image: prague.azurecr.io/augmentation:833
        command:
          - 'node'
          - 'dist/index.js'
        ports:
        - name: ui
          containerPort: 5000
      imagePullSecrets:
      - name: regsecret
---
apiVersion: v1
kind: Service
metadata:
  name: augmentation
  labels:
    app: augmentation
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
    targetPort: ui
  selector:
    app: augmentation
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
 name: augmentation
 namespace: default
 annotations:
   kubernetes.io/ingress.class: "nginx"
   ingress.kubernetes.io/ssl-redirect: "true"
spec:
 tls:
 - hosts:
   - "augmentation.wu2.prague.office-int.com"
   secretName: wu2-tls-certificate
 rules:
 - host: "augmentation.wu2.prague.office-int.com"
   http:
     paths:
     - path: /
       backend:
         serviceName: augmentation
         servicePort: 80