apiVersion: v1
kind: ConfigMap
metadata:
  name: elastalert-unhandledpromise
data:
  unhandledpromise.yaml: |
    name: Unhandled Promise
    type: any
    index: logstash-*
    filter:
    - query:
        query_string:
          query: "*UnhandledPromiseRejection*"
    alert:
    - "post"
    http_post_url: "https://sentry.wu2.prague.office-int.com/api/3/store/?sentry_version=7&sentry_key=344cbdea481f46baa1d3f5144c90b1f6&sentry_secret=0385ef41b1444e8ebff49c9a6b647485&sentry_client=elastalert"
    http_post_payload:
        timestamp: timestamp
        logger: kubernetes.pod_name
        level: level
        message: message
        extra: stack