apiVersion: v1
kind: ConfigMap
metadata:
  name: elastalert-unhandledpromise
data:    
  unhandledpromise.yaml: |
    name: Unhandled Promise Alert!
    type: frequency
    index: logstash-*
    num_events: 1
    timeframe:
        minutes: 1
    filter: 
    - query:
        query_string:
          query: "*UnhandledPromiseRejection*"
    alert:
    - "email"
    - "debug"
    realert:
        hours: 24
    email:
    - mdaumi@microsoft.com
    - kurtb@microsoft.com
    - steveluc@microsoft.com